language: csharp
solution: Dev.sln
script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log
mono:
  - latest
  - 3.12.0
